APPNAME=FET
VERSION=0

Name=Timetable Generator
Name[ru]=Генератор расписаний
Name[af]=Tydtabel genereerder
Name[sq]=Gjenerues i Tabelës Kohore
Name[ast]=Xenerador de tables d'horariu
Name[be]=Генэратар раскладаў
Name[bn]=সময়সূচী উদ্ভাবক
Name[bs]=Generator rasporeda časova
Name[pt_BR]=Gerador de grade de horários
Name[ca]=Generador d'horaris
Name[ca@valencia]=Generador d'horaris
Name[zh_HK]=時間表製作程式
Name[zh_TW]=時間表製作程式
Name[crh]=Üreteç Tarifesi
Name[zh_CN]=时间表生成器
Name[cs]=Tvorba rozvrhů
Name[da]=Tidsskema-generator
Name[nl]=Tijdtabelgenerator
Name[et]=Ajakava generaator
Name[fi]=Lukujärjestysten luoja
Name[fr]=Générateur d'emploi du temps
Name[gl]=Xerador de horarios
Name[de]=Stundenplanerstellung
Name[hu]=Órarend-generátor
Name[it]=Generatore di tabelle degli orari
Name[ja]=時間割作成ソフトウェア
Name[ky]=Жадыбал генератору
Name[lt]=Tvarkaraščių generatorius
Name[ms]=Penjana Jadual Waktu
Name[nb]=Timeplan-generator
Name[oc]=Generador d'emplec del temps
Name[fa]=ایجاد کننده برنامه
Name[pl]=Generator planu zajęć
Name[pt]=Criador de horários
Name[ro]=Generator de orar
Name[sk]=Tvorba rozvrhov
Name[sl]=Ustvarjalnik urnikov
Name[sv]=Schemagenerator
Name[es]=Generador de tablas de horario
Name[tr]=Üreteç Tarifesi
Name[uk]=Генератор розкладів
Name[vi]=Trình tạo thời gian biểu

[Linux]
EXECDIR=bin/
APPLICATION=fet
;APPEXEC=fet
;APPMIME=fet
;APPICON=fet
BINLINKS="fet,fet-cl"
EXECLINE=%APP% %f

[Windows]
APPEXEC=fet.exe
EXECDIR=
ASSOC_EXT=.fet
ASSOC_PROGID=FET.Main

